"""Build leak-free NL2Bash training views for InterCode-Bash.

Run as a module from the repository root, for example:

```
python -m compositional_intercode_bash.prepare_data sources
python -m compositional_intercode_bash.prepare_data provenance --exploratory
python -m compositional_intercode_bash.prepare_data procedures --hidden-size 2048
python -m compositional_intercode_bash.prepare_data views --setting sampled --data-seed 1729
```

Both modes remove every retrieved InterCode candidate source group.  A
``--primary`` run additionally requires the exact pinned 200-task source set
and marks the conservative split as paper-ready; ``--exploratory`` uses the
same deletion rule but can never be promoted into a formal run.
"""

from __future__ import annotations

import argparse
import collections
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

from .atomizer import (
    IneligibleCommand,
    atomize_command,
    count_static_head_group_support,
)
from .data_sources import (
    DEFAULT_CANONICAL_SPLIT_DIR,
    SOURCE_ARTIFACT_FILENAMES,
    materialize_sources,
    validate_materialized_sources,
)
from .induction import paired_one_standard_error_select, run_three_initializations
from .io_utils import (
    PACKAGE_ROOT,
    ensure_output_path,
    read_json,
    read_jsonl,
    sha256_directory,
    sha256_file,
    write_json,
    write_jsonl,
)
from .provenance import materialize_provenance
from .unigram import (
    ProcedureUnigramModel,
    enumerate_candidates,
    group_balanced_weights,
    piece_sort_key,
)
from .views import (
    MIN_PRIMARY_REGULAR_GROUPS,
    attach_segmentation_metadata,
    build_balanced_presentations,
    build_views,
    required_primary_ambiguous_groups,
    segmentation_metadata,
)


DEFAULT_ARTIFACT_DIR = PACKAGE_ROOT / "artifacts" / "default"
SOURCE_ARTIFACTS = tuple(SOURCE_ARTIFACT_FILENAMES)
PROVENANCE_OUTPUT_ARTIFACTS = (
    "adjudications",
    "groups",
    "provenance",
    "provenance_report",
    "derived_split",
    "derived_split_report",
)
PROVENANCE_ARTIFACTS = (
    *SOURCE_ARTIFACTS,
    *PROVENANCE_OUTPUT_ARTIFACTS,
)
PROCEDURE_EVIDENCE_ARTIFACTS = (
    "atoms",
    "atomization_report",
    "candidates",
    "capacity_selection",
    "pruning_paths",
    "procedure_grid",
)
PROCEDURE_ARTIFACTS = (
    "procedure_lexicon",
    "segmentations",
    "procedure_report",
    "training_boundary_gate",
    *PROCEDURE_EVIDENCE_ARTIFACTS,
)
VIEW_INPUT_ARTIFACTS = (
    *PROVENANCE_ARTIFACTS,
    *PROCEDURE_ARTIFACTS,
)


def _file_integrity(path: str | Path) -> dict[str, Any]:
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"Required experiment artifact is missing: {path}")
    return {
        "path": str(path.resolve()),
        "sha256": sha256_file(path),
    }


def _directory_integrity(path: str | Path) -> dict[str, Any]:
    path = Path(path)
    if not path.is_dir():
        raise FileNotFoundError(f"Required experiment directory is missing: {path}")
    return {
        "path": str(path.resolve()),
        "sha256": sha256_directory(path),
    }


def _input_hashes(
    integrity: Mapping[str, Any],
    names: Sequence[str],
) -> dict[str, str]:
    hashes: dict[str, str] = {}
    for name in names:
        value = integrity.get(name)
        if not isinstance(value, Mapping) or not isinstance(
            value.get("sha256"),
            str,
        ):
            raise ValueError(f"Integrity manifest lacks SHA-256 for {name}")
        hashes[name] = str(value["sha256"])
    return hashes


def _is_primary_integrity(integrity: Mapping[str, Any]) -> bool:
    return (
        integrity.get("primary_ready") is True
        and integrity.get("primary_run") is True
        and integrity.get("deny_policy") == "all_candidates"
    )


def _require_primary_integrity(
    integrity: Mapping[str, Any],
    *,
    artifact_kind: str,
) -> None:
    if not _is_primary_integrity(integrity):
        raise RuntimeError(
            f"--primary requires {artifact_kind} generated by a primary "
            "all-candidates provenance run. Exploratory artifacts cannot be "
            "promoted by passing --primary at a later stage."
        )


def load_provenance_integrity(
    artifact_dir: str | Path,
    *,
    require_primary: bool,
) -> dict[str, Any]:
    """Validate the provenance report and the files it is meant to bind."""

    artifact_dir = Path(artifact_dir)
    source_integrity = validate_materialized_sources(
        artifact_dir,
        require_canonical=require_primary,
    )
    report_path = artifact_dir / "provenance_report.json"
    adjudications_path = artifact_dir / "adjudications.used.jsonl"
    groups_path = artifact_dir / "groups.json"
    provenance_path = artifact_dir / "provenance.jsonl"
    derived_path = artifact_dir / "raw_pairs.grouped_and_split.jsonl"
    derived_report_path = artifact_dir / "derived_split_report.json"
    report = read_json(report_path)
    bound_outputs = {
        "adjudications_sha256": adjudications_path,
        "groups_sha256": groups_path,
        "provenance_sha256": provenance_path,
        "derived_split_sha256": derived_path,
        "derived_split_report_sha256": derived_report_path,
    }
    for field, path in bound_outputs.items():
        if report.get(field) != sha256_file(path):
            raise ValueError(
                f"{path.name} differs from provenance_report.json; rerun "
                "the provenance stage"
            )
    expected_source_inputs = _input_hashes(
        source_integrity,
        SOURCE_ARTIFACTS,
    )
    if report.get("input_sha256") != expected_source_inputs:
        raise ValueError(
            "provenance_report.json was generated from different source "
            "artifacts; rerun the provenance stage"
        )

    primary_ready = report.get("primary_ready") is True
    primary_run = report.get("primary_run") is True
    if primary_ready and (
        report.get("tasks") != 200
        or report.get("deny_policy") != "all_candidates"
        or report.get("unresolved_candidates_removed") is not True
        or report.get("candidate_union_group_count")
        != report.get("actual_deny_group_count")
    ):
        raise ValueError(
            "A primary-ready provenance report must conservatively remove every "
            "retrieved candidate group for the exact official 200-task set"
        )
    integrity = {
        **source_integrity,
        "primary_ready": primary_ready,
        "primary_run": primary_run,
        "deny_policy": report.get("deny_policy"),
        "adjudications": _file_integrity(adjudications_path),
        "groups": _file_integrity(groups_path),
        "provenance": _file_integrity(provenance_path),
        "provenance_report": _file_integrity(report_path),
        "derived_split": _file_integrity(derived_path),
        "derived_split_report": _file_integrity(derived_report_path),
    }
    if require_primary:
        _require_primary_integrity(
            integrity,
            artifact_kind="provenance artifacts",
        )
    return integrity


def load_procedure_integrity(
    artifact_dir: str | Path,
    provenance_integrity: Mapping[str, Any],
    *,
    require_primary: bool = False,
) -> dict[str, Any]:
    """Check that lexicon/segmentations came from the current provenance files."""

    artifact_dir = Path(artifact_dir)
    report_path = artifact_dir / "procedure_report.json"
    lexicon_path = artifact_dir / "procedure_lexicon.json"
    segmentations_path = artifact_dir / "segmentations.jsonl"
    boundary_gate_path = artifact_dir / "training_boundary_gate.json"
    evidence_paths = {
        "atoms": artifact_dir / "atoms.jsonl",
        "atomization_report": artifact_dir / "atomization_report.json",
        "candidates": artifact_dir / "candidates.jsonl",
        "capacity_selection": artifact_dir / "capacity_selection.json",
        "pruning_paths": artifact_dir / "pruning_paths.json",
    }
    procedure_grid_path = artifact_dir / "procedure_grid"
    report = read_json(report_path)
    current_inputs = _input_hashes(
        provenance_integrity,
        PROVENANCE_ARTIFACTS,
    )
    if report.get("input_sha256") != current_inputs:
        raise ValueError(
            "Procedure artifacts were generated from different provenance "
            "artifacts; rerun the procedures stage"
        )
    actual_lexicon_sha = sha256_file(lexicon_path)
    actual_segmentations_sha = sha256_file(segmentations_path)
    if report.get("procedure_lexicon_sha256") != actual_lexicon_sha:
        raise ValueError(
            "procedure_lexicon.json differs from procedure_report.json"
        )
    if report.get("segmentations_sha256") != actual_segmentations_sha:
        raise ValueError("segmentations.jsonl differs from procedure_report.json")
    actual_boundary_gate_sha = sha256_file(boundary_gate_path)
    if report.get("training_boundary_gate_sha256") != actual_boundary_gate_sha:
        raise ValueError(
            "training_boundary_gate.json differs from procedure_report.json"
        )
    evidence_integrity = {
        name: _file_integrity(path) for name, path in evidence_paths.items()
    }
    evidence_integrity["procedure_grid"] = _directory_integrity(
        procedure_grid_path
    )
    actual_grid_files = sorted(
        path.relative_to(procedure_grid_path).as_posix()
        for path in procedure_grid_path.rglob("*")
        if path.is_file()
    )
    if report.get("procedure_grid_files") != actual_grid_files:
        raise ValueError(
            "Procedure grid file list differs from procedure_report.json"
        )
    if report.get("evidence_sha256") != _input_hashes(
        evidence_integrity,
        PROCEDURE_EVIDENCE_ARTIFACTS,
    ):
        raise ValueError(
            "Procedure induction evidence differs from procedure_report.json"
        )

    try:
        model = ProcedureUnigramModel.from_dict(read_json(lexicon_path))
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError("procedure_lexicon.json is not a valid fitted model") from exc
    model_hash = model.model_hash()
    inventory_hash = model.inventory_hash()
    expected_model_fields = {
        "selected_k": model.size,
        "selected_lexicon_hash": model_hash,
        "procedure_model_hash": model_hash,
        "procedure_inventory_hash": inventory_hash,
    }
    for field, expected in expected_model_fields.items():
        if report.get(field) != expected:
            raise ValueError(
                f"procedure_report.json field {field!r} differs from "
                "procedure_lexicon.json"
            )
    for record in read_jsonl(segmentations_path):
        sample_id = record.get("sample_id", "<unknown>")
        for field, expected in (
            ("lexicon_hash", model_hash),
            ("procedure_model_hash", model_hash),
            ("procedure_inventory_hash", inventory_hash),
            ("procedure_count", model.size),
        ):
            if record.get(field) != expected:
                raise ValueError(
                    f"Segmentation field {field!r} differs from the procedure "
                    f"model for sample {sample_id}"
                )
    for field in ("primary_ready", "primary_run", "deny_policy"):
        if report.get(field) != provenance_integrity.get(field):
            raise ValueError(
                f"procedure_report.json field {field!r} differs from the "
                "bound provenance report"
            )

    integrity = {
        **dict(provenance_integrity),
        "procedure_lexicon": _file_integrity(lexicon_path),
        "segmentations": _file_integrity(segmentations_path),
        "procedure_report": _file_integrity(report_path),
        "training_boundary_gate": _file_integrity(boundary_gate_path),
        **evidence_integrity,
        "procedure_count": model.size,
        "procedure_model_hash": model_hash,
        "procedure_inventory_hash": inventory_hash,
    }
    if require_primary:
        _require_primary_integrity(
            integrity,
            artifact_kind="procedure artifacts",
        )
    return integrity


def load_view_integrity(
    artifact_dir: str | Path,
    procedure_integrity: Mapping[str, Any],
    *,
    setting: str,
    data_seed: int,
    require_primary: bool = False,
) -> dict[str, Any]:
    """Validate a boundary-view report and its complete upstream hash chain."""

    artifact_dir = Path(artifact_dir)
    report_path = artifact_dir / f"views.{setting}.{data_seed}.report.json"
    views_path = artifact_dir / f"views.{setting}.{data_seed}.jsonl"
    coverage_path = views_path.with_suffix(".coverage.json")
    presentations_path = artifact_dir / "training_presentations.jsonl"
    presentation_report_path = artifact_dir / "presentation_report.json"
    report = read_json(report_path)

    expected_inputs = _input_hashes(
        procedure_integrity,
        VIEW_INPUT_ARTIFACTS,
    )
    if report.get("input_sha256") != expected_inputs:
        raise ValueError(
            "Boundary views were generated from different provenance/procedure "
            "artifacts; rerun the views stage"
        )
    expected_outputs = {
        "views_sha256": sha256_file(views_path),
        "coverage_report_sha256": sha256_file(coverage_path),
        "training_presentations_sha256": sha256_file(presentations_path),
        "presentation_report_sha256": sha256_file(presentation_report_path),
    }
    for field, expected in expected_outputs.items():
        if report.get(field) != expected:
            raise ValueError(
                f"Boundary-view artifact for {field!r} differs from its report"
            )
    if report.get("setting") != setting or report.get("data_seed") != data_seed:
        raise ValueError("Boundary-view report setting/data_seed mismatch")
    model_hash = procedure_integrity.get("procedure_model_hash")
    inventory_hash = procedure_integrity.get("procedure_inventory_hash")
    procedure_count = procedure_integrity.get("procedure_count")
    for field, expected in (
        ("lexicon_hash", model_hash),
        ("procedure_model_hash", model_hash),
        ("procedure_inventory_hash", inventory_hash),
        ("procedure_count", procedure_count),
    ):
        if expected is None or report.get(field) != expected:
            raise ValueError(
                f"Boundary-view report field {field!r} differs from the "
                "bound procedure model"
            )
    view_count = 0
    for record in read_jsonl(views_path):
        view_count += 1
        view_id = record.get("view_id", "<unknown>")
        for field, expected in (
            ("setting", setting),
            ("data_seed", data_seed),
            ("lexicon_hash", model_hash),
            ("procedure_model_hash", model_hash),
            ("procedure_inventory_hash", inventory_hash),
            ("procedure_count", procedure_count),
        ):
            if record.get(field) != expected:
                raise ValueError(
                    f"Boundary view field {field!r} differs from its report "
                    f"for view {view_id}"
                )
    if report.get("presentations") != view_count:
        raise ValueError(
            "Boundary-view report presentation count differs from views JSONL"
        )
    coverage_report = read_json(coverage_path)
    for field in (
        "procedure_count",
        "minimum_procedure_exposures",
        "procedure_positive_counts",
        "uncovered_procedure_ids",
        "native_reserved_boundary",
        "native_procedure_positive_coverage",
        "native_procedure_count",
        "added_procedure_positive_coverage",
        "added_procedure_count",
    ):
        if coverage_report.get(field) != report.get(field):
            raise ValueError(
                f"Coverage report field {field!r} differs from the view report"
            )
    if coverage_report.get("uncovered_procedure_ids") != []:
        raise ValueError("Coverage report contains uncovered procedures")
    for field in ("primary_ready", "primary_run", "deny_policy"):
        if report.get(field) != procedure_integrity.get(field):
            raise ValueError(
                f"Boundary-view report field {field!r} differs from the "
                "bound provenance report"
            )

    integrity = {
        **dict(procedure_integrity),
        "training_presentations": _file_integrity(presentations_path),
        "presentation_report": _file_integrity(presentation_report_path),
        "coverage_report": _file_integrity(coverage_path),
        "views": _file_integrity(views_path),
        "view_report": _file_integrity(report_path),
    }
    if require_primary:
        _require_primary_integrity(
            integrity,
            artifact_kind="boundary-view artifacts",
        )
        if report.get("primary_requested") is not True:
            raise RuntimeError(
                "--primary requires views that were themselves built with "
                "--primary; an exploratory view report cannot be promoted later"
            )
    return integrity


def build_atom_records(
    derived_records: Sequence[Mapping[str, Any]],
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    active = [record for record in derived_records if record["derived_split"]]
    training = [record for record in active if record["derived_split"] == "TRAIN"]
    head_support = count_static_head_group_support(
        (record["template_group_id"], record["command_raw"]) for record in training
    )
    output: list[dict[str, Any]] = []
    exclusions: collections.Counter[str] = collections.Counter()
    split_counts: collections.Counter[str] = collections.Counter()
    for record in active:
        try:
            atomized = atomize_command(
                record["command_raw"],
                head_group_support=head_support,
                minimum_head_group_support=2,
            )
        except IneligibleCommand as exc:
            exclusions[str(exc)] += 1
            continue
        if "".join(atomized.base_chunks).encode("utf-8") != record[
            "command_raw"
        ].encode("utf-8"):
            raise AssertionError(f"UTF-8 atom round trip failed for {record['sample_id']}")
        split_counts[record["derived_split"]] += 1
        output.append(
            {
                "sample_id": record["sample_id"],
                "source_line": record["source_line"],
                "instruction_raw": record["instruction_raw"],
                "command_raw": record["command_raw"],
                "official_split": record["official_split"],
                "derived_split": record["derived_split"],
                "source_group_id": record["source_group_id"],
                "template_group_id": record["template_group_id"],
                "root_kind": atomized.root_kind,
                "atoms": [atom.to_dict() for atom in atomized.atoms],
                "base_chunks": list(atomized.base_chunks),
                "canonical_signatures": [
                    list(signature) for signature in atomized.signatures
                ],
            }
        )
    report = {
        "schema": "strict_flat_atoms_v1",
        "active_pairs_before_atomization": len(active),
        "eligible": len(output),
        "eligible_by_split": dict(split_counts),
        "excluded": dict(exclusions),
        "head_group_support": [
            {
                "connector": connector,
                "static_utility_head": head,
                "template_groups": support,
            }
            for (connector, head), support in sorted(head_support.items())
        ],
    }
    return output, report


def _reorder_selected_model(model: ProcedureUnigramModel) -> ProcedureUnigramModel:
    order = sorted(
        range(model.size),
        key=lambda index: (
            not model.mandatory[index],
            -float(model.theta[index]),
            piece_sort_key(model.pieces[index]),
        ),
    )
    return ProcedureUnigramModel(
        [model.pieces[index] for index in order],
        [float(model.theta[index]) for index in order],
        model.rho,
        mandatory=[model.mandatory[index] for index in order],
    )


def training_boundary_gate(
    train_records: Sequence[Mapping[str, Any]],
    model: ProcedureUnigramModel,
) -> dict[str, Any]:
    """Compute the exact A/R support gates before dev-based K selection.

    Ambiguity is cached per canonical atom sequence.  A template group enters
    pool A if any of its rows has more than one sufficiently probable
    fixed-count segmentation; all remaining groups enter pool R.
    """

    group_is_ambiguous: dict[str, bool] = {}
    long_groups: set[str] = set()
    ambiguity_by_sequence: dict[tuple[tuple[str, str], ...], bool] = {}
    for record in train_records:
        group_id = str(record["template_group_id"])
        sequence = tuple(
            (str(value[0]), str(value[1]))
            for value in record["canonical_signatures"]
        )
        if len(sequence) >= 3:
            long_groups.add(group_id)
        if sequence not in ambiguity_by_sequence:
            ambiguity_by_sequence[sequence] = bool(
                segmentation_metadata(model, sequence)["is_ambiguous"]
            )
        group_is_ambiguous[group_id] = (
            group_is_ambiguous.get(group_id, False)
            or ambiguity_by_sequence[sequence]
        )

    a_groups = {
        group_id
        for group_id, is_ambiguous in group_is_ambiguous.items()
        if is_ambiguous
    }
    r_groups = set(group_is_ambiguous) - a_groups
    required_a = required_primary_ambiguous_groups(len(long_groups))
    a_gate_passed = len(a_groups) >= required_a
    r_gate_passed = len(r_groups) >= MIN_PRIMARY_REGULAR_GROUPS
    return {
        "K": model.size,
        "procedure_model_hash": model.model_hash(),
        "A_groups": len(a_groups),
        "R_groups": len(r_groups),
        "L_ge_3_groups": len(long_groups),
        "required_A_groups": required_a,
        "A_gate_passed": a_gate_passed,
        "R_gate_passed": r_gate_passed,
        "primary_gate_passed": a_gate_passed and r_gate_passed,
        "exploratory_gate_passed": len(a_groups) >= 2 and len(r_groups) >= 2,
    }


def filter_models_by_training_boundary_gate(
    winners: Mapping[int, Any],
    train_records: Sequence[Mapping[str, Any]],
    *,
    require_primary: bool,
) -> tuple[dict[int, Any], dict[str, Any]]:
    """Keep only K values that can build views in the requested run mode."""

    gate_mode = "primary" if require_primary else "exploratory"
    gate_by_k: dict[int, dict[str, Any]] = {}
    eligible_winners: dict[int, Any] = {}
    for size, fitted in sorted(winners.items()):
        gate = training_boundary_gate(train_records, fitted.model)
        eligible = bool(gate[f"{gate_mode}_gate_passed"])
        gate["eligible_for_one_se"] = eligible
        gate_by_k[size] = gate
        if eligible:
            eligible_winners[size] = fitted
    report = {
        "schema": "training_boundary_gate_v1",
        "gate_mode": gate_mode,
        "candidate_k_count": len(winners),
        "eligible_k_count": len(eligible_winners),
        "per_k": [gate_by_k[size] for size in sorted(gate_by_k)],
    }
    return eligible_winners, report


def build_procedure_artifacts(
    derived_records: Sequence[Mapping[str, Any]],
    output_dir: str | Path,
    *,
    hidden_size: int,
    provenance_integrity: Mapping[str, Any],
    em_max_iterations: int = 100,
    bootstrap_replicates: int = 1000,
) -> tuple[ProcedureUnigramModel, list[dict[str, Any]]]:
    output_dir = ensure_output_path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    atom_records, atom_report = build_atom_records(derived_records)
    train_records = [
        record for record in atom_records if record["derived_split"] == "TRAIN"
    ]
    dev_records = [
        record for record in atom_records if record["derived_split"] == "DEV"
    ]
    if not train_records or not dev_records:
        raise RuntimeError("Strict-flat derived train/dev data must both be non-empty")

    candidates = enumerate_candidates(
        (
            record["template_group_id"],
            tuple(tuple(value) for value in record["canonical_signatures"]),
        )
        for record in train_records
    )
    if sum(candidate.mandatory for candidate in candidates) > hidden_size:
        raise RuntimeError(
            "Mandatory procedure count exceeds model hidden size; pairwise orthogonal "
            "initialization is impossible"
        )
    train_sequences = [
        tuple(tuple(value) for value in record["canonical_signatures"])
        for record in train_records
    ]
    train_group_ids = [record["template_group_id"] for record in train_records]
    train_weights = group_balanced_weights(train_group_ids)
    winners, paths = run_three_initializations(
        candidates,
        train_sequences,
        train_weights,
        hidden_size=hidden_size,
        em_max_iterations=em_max_iterations,
    )
    require_primary_gate = _is_primary_integrity(provenance_integrity)
    gate_mode = "primary" if require_primary_gate else "exploratory"
    eligible_winners, boundary_gate_report = (
        filter_models_by_training_boundary_gate(
            winners,
            train_records,
            require_primary=require_primary_gate,
        )
    )
    boundary_gate_path = output_dir / "training_boundary_gate.json"
    write_json(boundary_gate_path, boundary_gate_report)
    if not eligible_winners:
        raise RuntimeError(
            f"No candidate K passes the {gate_mode} training A/R boundary "
            "support gate; see training_boundary_gate.json"
        )

    dev_sequences = [
        tuple(tuple(value) for value in record["canonical_signatures"])
        for record in dev_records
    ]
    dev_group_ids = [record["template_group_id"] for record in dev_records]
    selected_k, selection_report = paired_one_standard_error_select(
        eligible_winners,
        dev_sequences,
        dev_group_ids,
        bootstrap_replicates=bootstrap_replicates,
    )
    selection_report = {
        **selection_report,
        "training_boundary_gate": boundary_gate_report,
    }
    selected = _reorder_selected_model(eligible_winners[selected_k].model)
    if selected.size > hidden_size:
        raise AssertionError("Selected procedure model cannot be initialized orthogonally")

    segmented = attach_segmentation_metadata(atom_records, selected)
    write_jsonl(output_dir / "atoms.jsonl", atom_records)
    write_json(output_dir / "atomization_report.json", atom_report)
    write_jsonl(
        output_dir / "candidates.jsonl",
        [candidate.to_dict() for candidate in candidates],
    )
    lexicon_path = output_dir / "procedure_lexicon.json"
    write_json(lexicon_path, selected.to_dict())
    write_json(output_dir / "capacity_selection.json", selection_report)
    segmentations_path = output_dir / "segmentations.jsonl"
    write_jsonl(segmentations_path, segmented)
    write_json(
        output_dir / "pruning_paths.json",
        {
            mode: [
                path[size].to_summary() for size in sorted(path, reverse=True)
            ]
            for mode, path in paths.items()
        },
    )
    grid_dir = output_dir / "procedure_grid"
    grid_dir.mkdir(parents=True, exist_ok=True)
    expected_grid_names = {
        f"K_{size:04d}.json" for size in winners
    }
    for existing in grid_dir.iterdir():
        if (
            existing.is_file()
            and existing.name.startswith("K_")
            and existing.suffix == ".json"
            and existing.name not in expected_grid_names
        ):
            existing.unlink()
        elif existing.name not in expected_grid_names:
            raise RuntimeError(
                f"Unexpected file in managed procedure grid: {existing}"
            )
    for size, fitted in winners.items():
        write_json(grid_dir / f"K_{size:04d}.json", fitted.model.to_dict())
    write_json(
        output_dir / "procedure_report.json",
        {
            "schema": "procedure_induction_v1",
            "candidate_count": len(candidates),
            "mandatory_count": sum(candidate.mandatory for candidate in candidates),
            "multi_atom_candidate_count": sum(
                len(candidate.piece) > 1 for candidate in candidates
            ),
            "hidden_size": hidden_size,
            "native_reserved_boundary": 247,
            "native_reserved_boundary_is_not_capacity": True,
            "selected_k": selected.size,
            "selected_uses_added_tokens": selected.size > 247,
            "selected_lexicon_hash": selected.model_hash(),
            "procedure_model_hash": selected.model_hash(),
            "procedure_inventory_hash": selected.inventory_hash(),
            "input_sha256": _input_hashes(
                provenance_integrity,
                PROVENANCE_ARTIFACTS,
            ),
            "primary_ready": bool(provenance_integrity["primary_ready"]),
            "primary_run": bool(provenance_integrity["primary_run"]),
            "deny_policy": provenance_integrity["deny_policy"],
            "training_boundary_gate_sha256": sha256_file(boundary_gate_path),
            "procedure_lexicon_sha256": sha256_file(lexicon_path),
            "segmentations_sha256": sha256_file(segmentations_path),
            "evidence_sha256": {
                "atoms": sha256_file(output_dir / "atoms.jsonl"),
                "atomization_report": sha256_file(
                    output_dir / "atomization_report.json"
                ),
                "candidates": sha256_file(output_dir / "candidates.jsonl"),
                "capacity_selection": sha256_file(
                    output_dir / "capacity_selection.json"
                ),
                "pruning_paths": sha256_file(output_dir / "pruning_paths.json"),
                "procedure_grid": sha256_directory(grid_dir),
            },
            "procedure_grid_files": sorted(expected_grid_names),
        },
    )
    return selected, segmented


def build_view_artifacts(
    segmented_records: Sequence[Mapping[str, Any]],
    model: ProcedureUnigramModel,
    output_dir: str | Path,
    *,
    input_integrity: Mapping[str, Any],
    setting: str,
    data_seed: int,
    epochs: int = 100,
    presentation_seed: int = 314159,
    minimum_procedure_exposures: int = 10,
    primary: bool = False,
) -> list[dict[str, Any]]:
    output_dir = ensure_output_path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    if primary:
        _require_primary_integrity(
            input_integrity,
            artifact_kind="procedure artifacts",
        )
    expected_model_hash = input_integrity.get("procedure_model_hash")
    expected_inventory_hash = input_integrity.get("procedure_inventory_hash")
    expected_count = input_integrity.get("procedure_count")
    if (
        expected_model_hash != model.model_hash()
        or expected_inventory_hash != model.inventory_hash()
        or expected_count != model.size
    ):
        raise ValueError(
            "Procedure model differs from the integrity manifest used to build views"
        )
    view_input_hashes = _input_hashes(
        input_integrity,
        VIEW_INPUT_ARTIFACTS,
    )
    train_records = [
        record
        for record in segmented_records
        if record["derived_split"] == "TRAIN"
    ]
    presentations, presentation_report = build_balanced_presentations(
        train_records,
        model,
        epochs=epochs,
        presentation_seed=presentation_seed,
        minimum_procedure_exposures=minimum_procedure_exposures,
        primary=primary,
    )
    views, view_report = build_views(
        presentations,
        train_records,
        model,
        setting=setting,
        data_seed=data_seed,
        minimum_procedure_exposures=minimum_procedure_exposures,
        primary=primary,
    )
    presentations_path = output_dir / "training_presentations.jsonl"
    presentation_report_path = output_dir / "presentation_report.json"
    write_jsonl(presentations_path, presentations)
    write_json(presentation_report_path, presentation_report)
    views_path = output_dir / f"views.{setting}.{data_seed}.jsonl"
    write_jsonl(views_path, views)
    coverage_path = views_path.with_suffix(".coverage.json")
    coverage_fields = (
        "procedure_count",
        "minimum_procedure_exposures",
        "procedure_positive_counts",
        "uncovered_procedure_ids",
        "native_reserved_boundary",
        "native_procedure_positive_coverage",
        "native_procedure_count",
        "added_procedure_positive_coverage",
        "added_procedure_count",
    )
    write_json(
        coverage_path,
        {
            "schema": "procedure_positive_coverage_v1",
            **{field: view_report[field] for field in coverage_fields},
        },
    )
    view_report = {
        **view_report,
        "primary_requested": bool(primary),
        "primary_ready": bool(input_integrity["primary_ready"]),
        "primary_run": bool(input_integrity["primary_run"]),
        "deny_policy": input_integrity["deny_policy"],
        "presentation_epochs": presentation_report["epochs"],
        "minimum_requested_epochs": presentation_report[
            "minimum_requested_epochs"
        ],
        "input_sha256": view_input_hashes,
        "views_sha256": sha256_file(views_path),
        "coverage_report_sha256": sha256_file(coverage_path),
        "training_presentations_sha256": sha256_file(presentations_path),
        "presentation_report_sha256": sha256_file(presentation_report_path),
    }
    write_json(output_dir / f"views.{setting}.{data_seed}.report.json", view_report)
    load_view_integrity(
        output_dir,
        input_integrity,
        setting=setting,
        data_seed=data_seed,
        require_primary=primary,
    )
    return views


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "stage",
        choices=("sources", "provenance", "procedures", "views", "all"),
    )
    parser.add_argument(
        "--nl2bash-root",
        default=str(PACKAGE_ROOT.parent / "datasets" / "nl2bash"),
    )
    parser.add_argument(
        "--intercode-root",
        default=str(PACKAGE_ROOT.parent / "datasets" / "intercode"),
    )
    parser.add_argument("--artifact-dir", default=str(DEFAULT_ARTIFACT_DIR))
    parser.add_argument(
        "--split-source",
        choices=("canonical", "legacy-replay"),
        default="canonical",
        help="Use the pinned released split by default; legacy replay is audit-only",
    )
    parser.add_argument(
        "--canonical-split-dir",
        default=str(DEFAULT_CANONICAL_SPLIT_DIR),
    )
    parser.add_argument(
        "--replay-python",
        default="/home/shilong/anaconda3/envs/tokmem/bin/python",
        help="Python executable for the isolated NL2Bash replay entrypoint",
    )
    parser.add_argument("--adjudications")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--primary", action="store_true")
    mode.add_argument("--exploratory", action="store_true")
    parser.add_argument("--hidden-size", type=int, default=2048)
    parser.add_argument("--em-max-iterations", type=int, default=100)
    parser.add_argument("--bootstrap-replicates", type=int, default=1000)
    parser.add_argument("--setting", choices=("map", "sampled"), default="sampled")
    parser.add_argument("--data-seed", type=int, default=1729)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--minimum-procedure-exposures", type=int, default=10)
    parser.add_argument("--presentation-seed", type=int, default=314159)
    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> None:
    args = parse_args(argv)
    artifact_dir = ensure_output_path(args.artifact_dir)
    artifact_dir.mkdir(parents=True, exist_ok=True)

    if args.stage in {"sources", "all"}:
        raw, tasks = materialize_sources(
            args.nl2bash_root,
            args.intercode_root,
            artifact_dir,
            split_source=args.split_source,
            canonical_split_dir=args.canonical_split_dir,
            replay_python=args.replay_python,
        )
    else:
        validate_materialized_sources(
            artifact_dir,
            require_canonical=args.primary,
        )
        raw = list(read_jsonl(artifact_dir / "raw_pairs.official.jsonl"))
        tasks = list(read_jsonl(artifact_dir / "intercode_tasks.jsonl"))

    if args.stage in {"provenance", "all"}:
        source_integrity = validate_materialized_sources(
            artifact_dir,
            require_canonical=args.primary,
        )
        derived = materialize_provenance(
            raw,
            tasks,
            args.nl2bash_root,
            artifact_dir,
            adjudications_path=args.adjudications,
            primary=args.primary,
            source_input_sha256=_input_hashes(
                source_integrity,
                SOURCE_ARTIFACTS,
            ),
        )
    elif args.stage in {"procedures", "views"}:
        derived = list(read_jsonl(artifact_dir / "raw_pairs.grouped_and_split.jsonl"))
    else:
        derived = []

    provenance_integrity = None
    if args.stage in {"procedures", "views", "all"}:
        provenance_integrity = load_provenance_integrity(
            artifact_dir,
            require_primary=args.primary,
        )

    if args.stage in {"procedures", "all"}:
        assert provenance_integrity is not None
        model, segmented = build_procedure_artifacts(
            derived,
            artifact_dir,
            hidden_size=args.hidden_size,
            provenance_integrity=provenance_integrity,
            em_max_iterations=args.em_max_iterations,
            bootstrap_replicates=args.bootstrap_replicates,
        )
    elif args.stage == "views":
        model = ProcedureUnigramModel.from_dict(
            read_json(artifact_dir / "procedure_lexicon.json")
        )
        segmented = list(read_jsonl(artifact_dir / "segmentations.jsonl"))
    else:
        model = None
        segmented = []

    if args.stage in {"views", "all"}:
        assert model is not None
        assert provenance_integrity is not None
        input_integrity = load_procedure_integrity(
            artifact_dir,
            provenance_integrity,
            require_primary=args.primary,
        )
        build_view_artifacts(
            segmented,
            model,
            artifact_dir,
            input_integrity=input_integrity,
            setting=args.setting,
            data_seed=args.data_seed,
            epochs=args.epochs,
            presentation_seed=args.presentation_seed,
            minimum_procedure_exposures=args.minimum_procedure_exposures,
            primary=args.primary,
        )


if __name__ == "__main__":
    main()
